### ISSUE TITLE
 Alcatrazの導入

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/DiarySampler#1]

**Comment by sotakenmotsu** [comment]
この過程で
<img width="881" alt="2017-02-02 11 29 44" src="https://cloud.githubusercontent.com/assets/19428366/22534965/22a020e2-e93b-11e6-9338-f5f4a44b98cd.png">
こうなるはずが
<img width="573" alt="2017-02-02 11 30 39" src="https://cloud.githubusercontent.com/assets/19428366/22534977/2d6ad99a-e93b-11e6-9123-490fb1246833.png">
こうなっちゃうんだけど

**Comment by s11y** [comment]
Alcatrazはとりあえずいれなくていいよ

**Comment by sotakenmotsu** [comment]
Realm入れるのに必要じゃないの？

**Comment by sotakenmotsu** [comment]
<img width="882" alt="2017-02-04 17 53 29" src="https://cloud.githubusercontent.com/assets/19428366/22617236/ebce612c-eb02-11e6-80d9-56a3687a6bf2.png">
<img width="577" alt="2017-02-04 17 53 40" src="https://cloud.githubusercontent.com/assets/19428366/22617235/ebce155a-eb02-11e6-9160-72420bbe175f.png">
こうなっちゃった

**Comment by s11y** [comment]
いや全然必要じゃない

**Comment by s11y** [comment]
Realmのモデルクラスつくるときの便利ツールだから、とりあえず`Swift`ファイルつくって、例えば`Sample`っていうモデルクラスをつくるときには、`Sample.swift`をつくって
```swift

import RealmSwift

class Sample: Object {
}

```
ってすればいいだけだから、全然いらないから無視していいよ

**Comment by sotakenmotsu** [comment]
`RealmSwift`は必要？

**Comment by s11y** [comment]
それは必要

**Comment by s11y** [comment]
だから今の`pod`のエラーは直さないといけない

**Comment by s11y** [comment]
エラーメッセージはググってみた？

**Comment by sotakenmotsu** [comment]
<img width="708" alt="2017-02-04 18 03 20" src="https://cloud.githubusercontent.com/assets/19428366/22617284/4d39f61e-eb04-11e6-8343-22b9f58a9e06.png">
これを順に実行してみる

**Comment by s11y** [comment]
OK

**Comment by s11y** [comment]
Good job!
