### ISSUE TITLE
Realm導入

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/DiarySampler#2]

**Comment by sotakenmotsu** [comment]
<img width="734" alt="2017-02-05 20 36 52" src="https://cloud.githubusercontent.com/assets/19428366/22625849/0e6d15f8-ebe3-11e6-8ee4-c160429d2bea.png">
`cocoapod`と`swift`でバージョンを設定しろみたいなエラーだけど、解決方法がわからない

**Comment by sotakenmotsu** [comment]
<img width="721" alt="2017-02-05 20 45 44" src="https://cloud.githubusercontent.com/assets/19428366/22625899/1d313910-ebe4-11e6-83e1-74a5c669ad1d.png">

**Comment by s11y** [comment]
ググってみてどんな記事見た？

**Comment by sotakenmotsu** [comment]
http://techblog.wanabe.net/entry/Xcode-Simulator
とか
http://qiita.com/yokomotod/items/a96ab24f01a91d54d399
とか
https://teratail.com/questions/49899
やってみたけどうまくいかない

**Comment by s11y** [comment]
いいね
しっかり見てるね
これがヒント！
<img width="718" alt="2017-02-06 12 04 52" src="https://cloud.githubusercontent.com/assets/11238461/22634839/730baa4a-ec71-11e6-98b1-c58af3214bdd.png">

**Comment by s11y** [comment]
最初のURL http://techblog.wanabe.net/entry/Xcode-Simulator にあるよ
`Use Legacy Swift Language Version`っていうのを`No`にすればいいから、あとはどっちのプロジェクトファイルの`Build Setting`を変更すればいいかだけだね

**Comment by sotakenmotsu** [comment]
どっちも`No`にしたけどまだエラー出てるよ

**Comment by sotakenmotsu** [comment]
<img width="625" alt="2017-02-06 18 24 21" src="https://cloud.githubusercontent.com/assets/19428366/22641315/940b42aa-ec99-11e6-8e15-cbcafc56d73b.png">
この`RealmSwift`についてもっていうのがよくわからない

**Comment by sotakenmotsu** [comment]
`Pods`の`Build Settings`も`No`にしたけどダメだった

**Comment by s11y** [comment]
noにしてコマンドBしても無理かい？

**Comment by sotakenmotsu** [comment]
うん

**Comment by s11y** [comment]
ちゃんと、`xcworkspace`のほう開いてる？
あと、`Podfile.lock`のほう見せて

**Comment by sotakenmotsu** [comment]
<img width="338" alt="2017-02-07 17 08 24" src="https://cloud.githubusercontent.com/assets/19428366/22682776/0ee7131e-ed58-11e6-9bf2-0e95b44ef730.png">
ごめん、runできた

**Comment by s11y** [comment]
OK
