### ISSUE TITLE
カレンダーおかしい

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/DiarySampler#4]

**Comment by sotakenmotsu** [comment]
カレンダーの一週間が６日しかない

**Comment by sotakenmotsu** [comment]
<img width="322" alt="2017-02-07 22 17 32" src="https://cloud.githubusercontent.com/assets/19428366/22692649/45793ec2-ed83-11e6-9f87-4dde278dcbdf.png">
こういうこと

**Comment by s11y** [comment]
サイズ見切れてるだけちゃうか？

**Comment by s11y** [comment]
リサイズの方法いろいろ試してみて

**Comment by s11y** [comment]
Main.storyboard見てカレンダーのサイズ見直そう

**Comment by sotakenmotsu** [comment]
<img width="322" alt="2017-02-08 19 48 16" src="https://cloud.githubusercontent.com/assets/19428366/22734037/97b09c58-ee37-11e6-86b4-42ec1d59c1a3.png">
大きさ間違えてた

**Comment by s11y** [comment]
Good Job!
